const BOXES = [
  {
    "id": "TG001",
    "image": "images/boxes/IMG_2957.jpeg",
    "models": [
      "Redmi 10A",
      "Redmi 10X 5G",
      "Redmi 9A",
      "Redmi 9C",
      "Redmi 9i",
      "Redmi K23",
      "POCO C3",
      "POCO C31",
      "POCO M5",
      "Samsung A12",
      "Samsung A02S",
      "Samsung A025",
      "Samsung A032",
      "Samsung A035",
      "Samsung A03",
      "Samsung A03S",
      "Samsung A03 Core",
      "Samsung A04",
      "Samsung A04S",
      "Samsung A04 Core",
      "Samsung F04",
      "Samsung M04",
      "Samsung M02S",
      "Samsung A23 4G",
      "Vivo Y16",
      "Vivo Y37 5G"
    ]
  },
  {
    "id": "TG002",
    "image": "images/boxes/IMG_2958.jpeg",
    "models": [
      "Samsung A16",
      "Samsung A17",
      "Samsung A26",
      "Samsung F16 5G",
      "Samsung F36",
      "Samsung M16 5G",
      "Samsung M36"
    ]
  },
  {
    "id": "TG003",
    "image": "images/boxes/IMG_2959.jpeg",
    "models": [
      "Realme C55",
      "Narzo N55",
      "OPPO A1 5G",
      "Realme F23",
      "Realme K11Y",
      "Realme 11 5G",
      "OPPO A58 4G",
      "Narzo 60X",
      "OPPO A79 5G",
      "Realme C67",
      "Realme 12 5G",
      "Realme C63 5G",
      "Realme C65",
      "Realme 12X",
      "Vivo T3X",
      "Realme 12 Lite",
      "OPPO A60",
      "Vivo Y38",
      "Narzo 70X",
      "Narzo N65 5G",
      "iQOO Z9X",
      "Vivo Y58",
      "OPPO A3 Pro India",
      "OPPO K12X 5G",
      "OPPO A3X",
      "Realme 13 5G",
      "OPPO A80 5G",
      "OPPO A3 5G",
      "Realme 14X 5G",
      "Realme 14X India",
      "Realme C75",
      "Realme C73"
    ]
  },
  {
    "id": "TG004",
    "image": "images/boxes/IMG_2960.jpeg",
    "models": [
      "Redmi Note 10 4G",
      "Redmi Note 10S",
      "Redmi Note 11 Global",
      "Redmi Note 11S 4G",
      "Redmi Note 12S",
      "POCO M4 Pro 4G",
      "Redmi Note 11SE India",
      "POCO M5S"
    ]
  },
  {
    "id": "TG005",
    "image": "images/boxes/IMG_2961.jpeg",
    "models": [
      "Realme 9i",
      "Realme 9 Pro",
      "Realme C17",
      "Realme 7i",
      "Realme V25",
      "OPPO A32",
      "OPPO A33 2020",
      "OPPO A36",
      "OPPO A53 2020",
      "OPPO A54 4G",
      "OPPO A55 4G",
      "Samsung A76",
      "Redmi Note 12T Pro"
    ]
  },
  {
    "id": "TG006",
    "image": "images/boxes/IMG_2962(1).jpeg",
    "variant": "BLACK",
    "models": [
      "Vivo Y11 2019",
      "Vivo Y12",
      "Vivo Y12i",
      "Vivo Y15",
      "Vivo Y15A",
      "Vivo Y15S",
      "Vivo Y17",
      "Vivo Y02",
      "Vivo Y3",
      "Vivo Y3S",
      "Vivo U10",
      "Samsung M10S",
      "Samsung A30S"
    ]
  },
  {
    "id": "TG007",
    "image": "images/boxes/IMG_2963.jpeg",
    "models": [
      "Samsung A14",
      "Samsung M14",
      "Samsung E14 5G",
      "Samsung A22 5G",
      "Tecno Camon 12",
      "Itel S16"
    ]
  },
  {
    "id": "TG008",
    "image": "images/boxes/IMG_2964.jpeg",
    "models": [
      "Vivo V15 Pro",
      "Redmi K20",
      "Redmi K20 Pro",
      "POCO F2",
      "POCO F2 Pro",
      "Samsung S21 FE",
      "Huawei Nova 7i",
      "Huawei P40 Lite",
      "OPPO Reno"
    ]
  },
  {
    "id": "TG009",
    "image": "images/boxes/IMG_2965(1).jpeg",
    "variant": "BLACK",
    "models": [
      "Motorola G14",
      "Motorola G32",
      "Motorola G54",
      "Motorola G62",
      "Motorola G64",
      "Motorola S047"
    ]
  },
  {
    "id": "TG010",
    "image": "images/boxes/IMG_2966(1).jpeg",
    "models": [
      "Realme C65",
      "Realme C67 5G",
      "Realme C75X",
      "Realme 11 5G",
      "Realme 11X 5G",
      "Realme 12 5G",
      "Realme 12X 5G",
      "Realme P3X 5G",
      "Realme P3 Lite",
      "Narzo 70X",
      "Narzo 80X",
      "Narzo N65",
      "OPPO A1 5G",
      "OPPO A3X",
      "OPPO A3 Pro 5G",
      "OPPO A5i",
      "OPPO A5X",
      "OPPO A5 Pro",
      "OPPO A58 4G",
      "OPPO A60",
      "OPPO A79 5G",
      "Vivo Y19S",
      "Vivo Y21D",
      "Vivo Y31 5G",
      "Vivo Y31 Pro",
      "Vivo Y200+",
      "Vivo Y58 5G",
      "Vivo Y37 Pro",
      "Vivo Y28 4G",
      "Vivo Y29 5G",
      "Vivo Y38",
      "Vivo Y39 5G",
      "Vivo Y200T",
      "Vivo Y300I",
      "Vivo Y300T",
      "Vivo T3X 5G",
      "Vivo T4X",
      "iQOO Z10X",
      "OnePlus Nord N30",
      "OnePlus Nord N30 SE",
      "Motorola G05",
      "Motorola G15"
    ]
  },
  {
    "id": "TG011",
    "image": "images/boxes/IMG_2967(1).jpeg",
    "models": [
      "Realme 2",
      "Realme A3S",
      "Realme A5",
      "Realme C1",
      "Realme A3",
      "Realme F7",
      "Oppo R15",
      "Vivo Y81",
      "Vivo Y81S",
      "Vivo Y83",
      "Vivo Y83 Pro",
      "Vivo Y85",
      "Vivo V9",
      "Vivo V9 Pro",
      "Vivo X21",
      "Vivo X21A",
      "OnePlus 6"
    ]
  },
  {
    "id": "TG012",
    "image": "images/boxes/IMG_2969(1).jpeg",
    "models": [
      "Oppo F19",
      "Oppo F19S",
      "Oppo F19 Pro",
      "Oppo F19 Pro+",
      "Oppo F17 Pro",
      "Oppo F21 Pro",
      "Oppo F21S Pro",
      "Oppo A74 4G",
      "Oppo A78 4G",
      "Oppo A93",
      "Oppo A95 5G",
      "Oppo A96 5G",
      "Realme 7 Pro",
      "Realme X7",
      "Realme X7 Pro",
      "Realme 9 Pro",
      "Realme 10 4G",
      "Realme 10 5G",
      "Realme GT2"
    ]
  },
  {
    "id": "TG013",
    "image": "images/boxes/IMG_2970(1).jpeg",
    "models": [
      "Samsung A05",
      "Samsung A06",
      "Samsung M05",
      "Samsung F06 5G",
      "Redmi 13C",
      "Oppo A3X",
      "Xiaomi POCO C65",
      "Xiaomi M6 5G"
    ]
  },
  {
    "id": "TG014",
    "image": "images/boxes/IMG_2971(1).jpeg",
    "variant": "BLACK",
    "models": [
      "Realme 5",
      "Realme 5i",
      "Realme 5S",
      "Realme C3",
      "Realme C11",
      "Realme C12",
      "Realme C15",
      "Realme C20",
      "Realme C21",
      "Realme C21Y",
      "Realme C25",
      "Realme C25S",
      "Realme C25Y",
      "Realme C30",
      "Realme C30S",
      "Realme V30",
      "Realme C31",
      "Realme C33",
      "Realme C35",
      "Realme 10 5G",
      "Realme 10T",
      "Realme Narzo 10",
      "Realme Narzo 10A",
      "Realme Narzo 50A Prime",
      "Oppo A2",
      "Oppo A2M",
      "Oppo A2X",
      "Oppo A57",
      "Oppo A58",
      "Oppo A77",
      "Oppo A78",
      "Oppo A16",
      "Oppo A16K",
      "Oppo A16E",
      "Oppo A17",
      "Oppo A17K",
      "Oppo A18",
      "Oppo A31 2020",
      "Oppo A35 2020",
      "Oppo A35 2021",
      "Oppo A38",
      "Oppo A53S",
      "Oppo A54S 5G",
      "Oppo A55 2021",
      "Oppo A55S",
      "Oppo A56",
      "Oppo A57 5G",
      "Oppo A57E",
      "Oppo A59 5G",
      "Oppo A77S",
      "Vivo Y51 2020",
      "Vivo Y31S",
      "Vivo Y31 2021",
      "Vivo Y53S",
      "Vivo Y72 5G",
      "Vivo Y20",
      "Vivo Y20i",
      "Vivo Y20T",
      "Vivo Y20S",
      "Vivo Y21",
      "Vivo Y22",
      "Vivo Y22S",
      "Vivo Y28 5G",
      "Vivo Y32",
      "Vivo Y33",
      "Vivo Y33S",
      "Vivo Y35",
      "Vivo Y51A",
      "Vivo Y52S",
      "Vivo Y52T",
      "Vivo Y74",
      "Vivo Y75S",
      "Vivo Y76 5G",
      "Vivo Y77",
      "Vivo Y77S",
      "Vivo Y11S",
      "Vivo Y12 2023",
      "Vivo Y12A",
      "Vivo Y12S",
      "Vivo Y17S",
      "Vivo Y18E",
      "Vivo Y02",
      "Vivo Y02S",
      "Vivo Y02A",
      "Vivo Y02T",
      "Vivo Y03",
      "Vivo T2X",
      "Vivo T1",
      "Vivo T1S",
      "Vivo T1X",
      "Vivo T3 Lite",
      "iQOO Z3",
      "Samsung A13",
      "Samsung A13 5G",
      "Samsung M13",
      "Samsung F13",
      "Samsung A23 5G",
      "Samsung M23",
      "Samsung M33",
      "Samsung F12",
      "Samsung M12",
      "Samsung M02",
      "Samsung F02S",
      "Oppo A32 5G",
      "Oppo Vision 2S",
      "Infinix Hot 8",
      "Infinix Hot 10",
      "Infinix Hot 11",
      "Infinix Hot 30i",
      "Tecno Spark 5",
      "Tecno Spark 6",
      "Tecno Spark 4",
      "Tecno Spark 8",
      "Tecno Spark 8P",
      "Tecno Pova 5",
      "Tecno Pova 5 Lite",
      "OnePlus Nord N30",
      "OnePlus Nord N30 SE",
      "Motorola G8 Power Lite",
      "Motorola G9",
      "Motorola G9 Play",
      "Motorola G10",
      "Motorola G10 Power",
      "Motorola G20",
      "Motorola G30",
      "Motorola G50",
      "Motorola E7",
      "Motorola E7 Plus",
      "Motorola E7 Power",
      "Honor X5+",
      "Honor X6 5G",
      "Honor X6B",
      "Honor X8 5G",
      "Huawei Nova Y61",
      "Xiaomi POCO M4 5G",
      "Realme 10X Pro",
      "Tecno Pop 6 Pro",
      "Tecno Pop 7",
      "Tecno Spark 6 Go",
      "Tecno Spark 8C",
      "Tecno Spark 9",
      "Tecno Spark 9T",
      "Tecno Pop 10",
      "Itel A06",
      "Itel P36",
      "Itel P40",
      "Itel P40+",
      "Itel S17",
      "Itel A50C",
      "Oppo A58 Pro",
      "Oppo A49"
    ]
  },
  {
    "id": "TG016",
    "image": "images/boxes/IMG_2973(1).jpeg",
    "variant": "BLACK",
    "models": [
      "1+1 3R"
    ]
  }
];
